---
title: "COVID Challenge"
author: "Julia Thompson"
date: "4/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)

#library(keras)
#install_keras()
library(keras)
library(tensorflow)
```

## Loading the Data

```{r}
# deaths
deaths = read_excel("./deaths_global.xlsx")

# cases
cases = read_excel("./confirmed_global.xlsx")

# revocered
recovered = read_excel("./recovered_global.xlsx")
```

## Data Cleaning

```{r}
cases_long = cases %>% 
  pivot_longer(
    cols = `43852`:`43943`,
    names_to = "date",
    values_to = "cases"
  ) %>% 
  mutate(
    date = as.Date(as.numeric(date), origin = "1899-12-30")
  )

deaths_long = deaths %>% 
  pivot_longer(
    cols = `43852`:`43943`,
    names_to = "date",
    values_to = "deaths"
  ) %>% 
  mutate(
    date = as.Date(as.numeric(date), origin = "1899-12-30")
  )

recovered_long = recovered %>% 
  pivot_longer(
    cols = `43852`:`43943`,
    names_to = "date",
    values_to = "recovered"
  ) %>% 
  mutate(
    date = as.Date(as.numeric(date), origin = "1899-12-30")
  )
```

## Visualization

Focus on Spain first:

```{r}
spain_cases = cases_long %>% 
  filter(`Country/Region`=="Spain")

a = ggplot(spain_cases, aes(x = date, y = cases)) + 
  geom_line(aes(color = `Country/Region`), size = 1)

a + theme(legend.position = "none")
```

## Time series forecasting

```{r}
diffed = diff(spain_cases$cases, differences = 1)
head(diffed)
```

```{r}
lag_transform <- function(x, k= 1){
    
      lagged =  c(rep(NA, k), x[1:(length(x)-k)])
      DF = as.data.frame(cbind(lagged, x))
      colnames(DF) <- c( paste0('x-', k), 'x')
      DF[is.na(DF)] <- 0
      return(DF)
}
supervised = lag_transform(diffed, 1)
head(supervised)
```

```{r}
N = nrow(supervised)
n = round(N *0.8, digits = 0)
train = supervised[1:n, ]
test  = supervised[(n+1):N,  ]
```

```{r}
scale_data = function(train, test, feature_range = c(0, 1)) {
  x = train
  fr_min = feature_range[1]
  fr_max = feature_range[2]
  std_train = ((x - min(x) ) / (max(x) - min(x)  ))
  std_test  = ((test - min(x) ) / (max(x) - min(x)  ))
  
  scaled_train = std_train *(fr_max -fr_min) + fr_min
  scaled_test = std_test *(fr_max -fr_min) + fr_min
  
  return( list(scaled_train = as.vector(scaled_train), scaled_test = as.vector(scaled_test) ,scaler= c(min =min(x), max = max(x))) )
  
}


Scaled = scale_data(train, test, c(-1, 1))

y_train = Scaled$scaled_train[, 2]
x_train = Scaled$scaled_train[, 1]

y_test = Scaled$scaled_test[, 2]
x_test = Scaled$scaled_test[, 1]
```

```{r}
invert_scaling = function(scaled, scaler, feature_range = c(0, 1)){
  min = scaler[1]
  max = scaler[2]
  t = length(scaled)
  mins = feature_range[1]
  maxs = feature_range[2]
  inverted_dfs = numeric(t)
  
  for( i in 1:t){
    X = (scaled[i]- mins)/(maxs - mins)
    rawValues = X *(max - min) + min
    inverted_dfs[i] <- rawValues
  }
  return(inverted_dfs)
}
```

```{r}
dim(x_train) <- c(length(x_train), 1, 1)

# specify required arguments
X_shape2 = dim(x_train)[2]
X_shape3 = dim(x_train)[3]
batch_size = 1                # must be a common factor of both the train and test samples
units = 1          # can adjust this, in model tuninig phase

model <- keras_model_sequential() 
model%>%
  layer_lstm(units, batch_input_shape = c(batch_size, X_shape2, X_shape3), stateful= TRUE)%>%
  layer_dense(units = 1)
```

```{r}
model %>% compile(
  loss = 'mean_squared_error',
  optimizer = optimizer_adam( lr= 0.02, decay = 1e-6 ),  
  metrics = c('accuracy')
)

summary(model)
```

```{r}
Epochs = 50   
for(i in 1:Epochs ){
  model %>% fit(x_train, y_train, epochs=1, batch_size=batch_size, verbose=1, shuffle=FALSE)
  model %>% reset_states()
}
```

```{r}
L = length(x_test)
scaler = Scaled$scaler
predictions = numeric(L)

for(i in 1:L){
     X = x_test[i]
     dim(X) = c(1,1,1)
     yhat = model %>% predict(X, batch_size=batch_size)
     # invert scaling
     yhat = invert_scaling(yhat, scaler,  c(-1, 1))
     # invert differencing
     yhat  = yhat + spain_cases$cases[(n+i)]
     # store
     predictions[i] <- yhat
}
```

```{r}
# predictions are for observations 65 through the end, same as the testing dataset.

date_pred = spain_cases$date[66:92]
spain_pred = cbind.data.frame(date_pred, predictions)

ggplot(spain_cases, aes(x = date, y = cases)) + 
  geom_line() +
  geom_line(data = spain_pred, aes(x = date_pred, y = predictions, color = "red"))


```

Credit to: http://rwanjohi.rbind.io/2018/04/05/time-series-forecasting-using-lstm-in-r/